### ISSUE TITLE
Drop the dependency on kernel32-sys

### ISSUE THREAD

**Issue by paride** [mitsuhiko/clicolors-control#7]
As far as I can tell, kernel32-sys is not necessary anymore when using winapi-0.3. Look for example at what has been done here when updating from winapi 0.2 to 0.3:

https://github.com/oconnor663/os_pipe.rs/commit/17d549af88b994b5209c90a37b36a26da1c8c03a

kernel32-sys was part of winapi-0.2, meaning that you now depend on both versions of the library. Could you try to drop the dependency on kernel32-sys and tag a new release?

This will ease the downstream packaging (in Debian in particular). Thank you!

**Comment by atouchet** [comment]
This was done in https://github.com/mitsuhiko/clicolors-control/commit/80ed6c9cd239bcad35cacc67a28f19a2597398a5.
